"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LocalizeContext = exports.T = exports.useLocale = exports.useLocalizedString = exports.useLocalizedPlural = exports.useLocalize = exports.LocalizeProvider = exports.i18nJsBundleFallback = exports.i18nextBundleFallback = exports.jsonBundleFallback = exports.memoryStorageAdapter = exports.fileSystemAdapter = exports.asyncStorageAdapter = exports.normalizeLocale = exports.detectDeviceLocale = exports.parseLocalBundleJson = exports.parseLocalBundle = exports.bundleLoader = exports.LocalizeLogEntry = exports.isRTL = exports.interpolateNamed = exports.interpolate = exports.selectPluralForm = exports.SDK_VERSION = exports.DEFAULT_PLATFORM = exports.DEFAULT_BASE_URL = exports.createLocalizeClient = exports.LocalizeSDK = void 0;
var LocalizeSDK_1 = require("./LocalizeSDK");
Object.defineProperty(exports, "LocalizeSDK", { enumerable: true, get: function () { return LocalizeSDK_1.LocalizeSDK; } });
var createLocalizeClient_1 = require("./createLocalizeClient");
Object.defineProperty(exports, "createLocalizeClient", { enumerable: true, get: function () { return createLocalizeClient_1.createLocalizeClient; } });
var LocalizeConfig_1 = require("./LocalizeConfig");
Object.defineProperty(exports, "DEFAULT_BASE_URL", { enumerable: true, get: function () { return LocalizeConfig_1.DEFAULT_BASE_URL; } });
Object.defineProperty(exports, "DEFAULT_PLATFORM", { enumerable: true, get: function () { return LocalizeConfig_1.DEFAULT_PLATFORM; } });
Object.defineProperty(exports, "SDK_VERSION", { enumerable: true, get: function () { return LocalizeConfig_1.SDK_VERSION; } });
var plural_1 = require("./domain/plural");
Object.defineProperty(exports, "selectPluralForm", { enumerable: true, get: function () { return plural_1.selectPluralForm; } });
var interpolation_1 = require("./domain/interpolation");
Object.defineProperty(exports, "interpolate", { enumerable: true, get: function () { return interpolation_1.interpolate; } });
Object.defineProperty(exports, "interpolateNamed", { enumerable: true, get: function () { return interpolation_1.interpolateNamed; } });
var rtl_1 = require("./internal/rtl");
Object.defineProperty(exports, "isRTL", { enumerable: true, get: function () { return rtl_1.isRTL; } });
var logger_1 = require("./internal/logger");
Object.defineProperty(exports, "LocalizeLogEntry", { enumerable: true, get: function () { return logger_1.LocalizeLogEntry; } });
var loader_1 = require("./adapters/loader");
Object.defineProperty(exports, "bundleLoader", { enumerable: true, get: function () { return loader_1.bundleLoader; } });
Object.defineProperty(exports, "parseLocalBundle", { enumerable: true, get: function () { return loader_1.parseLocalBundle; } });
Object.defineProperty(exports, "parseLocalBundleJson", { enumerable: true, get: function () { return loader_1.parseLocalBundleJson; } });
var deviceLocale_1 = require("./adapters/deviceLocale");
Object.defineProperty(exports, "detectDeviceLocale", { enumerable: true, get: function () { return deviceLocale_1.detectDeviceLocale; } });
Object.defineProperty(exports, "normalizeLocale", { enumerable: true, get: function () { return deviceLocale_1.normalizeLocale; } });
var storage_1 = require("./adapters/storage");
Object.defineProperty(exports, "asyncStorageAdapter", { enumerable: true, get: function () { return storage_1.asyncStorageAdapter; } });
Object.defineProperty(exports, "fileSystemAdapter", { enumerable: true, get: function () { return storage_1.fileSystemAdapter; } });
Object.defineProperty(exports, "memoryStorageAdapter", { enumerable: true, get: function () { return storage_1.memoryStorageAdapter; } });
var json_1 = require("./adapters/bundleFallback/json");
Object.defineProperty(exports, "jsonBundleFallback", { enumerable: true, get: function () { return json_1.jsonBundleFallback; } });
var i18next_1 = require("./adapters/bundleFallback/i18next");
Object.defineProperty(exports, "i18nextBundleFallback", { enumerable: true, get: function () { return i18next_1.i18nextBundleFallback; } });
var i18nJs_1 = require("./adapters/bundleFallback/i18nJs");
Object.defineProperty(exports, "i18nJsBundleFallback", { enumerable: true, get: function () { return i18nJs_1.i18nJsBundleFallback; } });
var LocalizeProvider_1 = require("./react/LocalizeProvider");
Object.defineProperty(exports, "LocalizeProvider", { enumerable: true, get: function () { return LocalizeProvider_1.LocalizeProvider; } });
var hooks_1 = require("./react/hooks");
Object.defineProperty(exports, "useLocalize", { enumerable: true, get: function () { return hooks_1.useLocalize; } });
Object.defineProperty(exports, "useLocalizedPlural", { enumerable: true, get: function () { return hooks_1.useLocalizedPlural; } });
Object.defineProperty(exports, "useLocalizedString", { enumerable: true, get: function () { return hooks_1.useLocalizedString; } });
Object.defineProperty(exports, "useLocale", { enumerable: true, get: function () { return hooks_1.useLocale; } });
var T_1 = require("./react/T");
Object.defineProperty(exports, "T", { enumerable: true, get: function () { return T_1.T; } });
var context_1 = require("./react/context");
Object.defineProperty(exports, "LocalizeContext", { enumerable: true, get: function () { return context_1.LocalizeContext; } });
